## Python Modules

In [1]:
import tertiary as tt

In [2]:
tt.calculator(23,5)

Enter "a" for addition 
 Enter "s" for substraction 
 Enter "m" for multiplication
 Enter "d" for divisions


18

In [3]:
tt.calculator(5,8)


Enter "a" for addition 
 Enter "s" for substraction 
 Enter "m" for multiplication
 Enter "d" for divisionm


40

In [4]:
from mathematics import product as p

In [5]:
p(3,4,5)

the product of all the numbers is  60


In [6]:
import mathematics as ma

In [7]:
ma.addition(67,89)

the summation of the numbers is 156


In [8]:
ma.difference(21,89)

the difference of the numbers is -68


In [9]:
ma.product(43,2)

the product of all the numbers is  86


In [10]:
import math

In [11]:
math.factorial(8)

40320

## Numpy (Numerical Python)

In [12]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy as np

In [16]:
a = np.array([2,4,6,8,10])

In [17]:
a

array([ 2,  4,  6,  8, 10])

In [18]:
a[0]

2

In [19]:
a[:3]

array([2, 4, 6])

In [20]:
a[2:]

array([ 6,  8, 10])

In [21]:
a.dtype

dtype('int32')

In [22]:
b =[2,4,6,8,10]

In [23]:
a*2

array([ 4,  8, 12, 16, 20])

In [25]:
b*2

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]

In [26]:
a/2

array([1., 2., 3., 4., 5.])

In [28]:
c = np.array([[1,2,3],
            [4,5,6]])

In [29]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
c[0][2]

3

In [33]:
c[1][1]

5

In [34]:
c*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [35]:
c.shape

(2, 3)

In [36]:
c.ndim

2

In [37]:
c.sum()

21

In [38]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
c.min()

1

In [40]:
c.max()

6

In [41]:
c.argmax()

5

In [42]:
c.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])